<img style="float: right;width: 100px" src="https://www.enib.fr/images/logo-enib-accueil.jpg">

<div>
    <p><h3>Asservissement (S6)</h3></p>
    <p>Année 2020 - 2021</p>
    <p><em>Equipe Pédagogique</em></p>
</div>

<div style="text-align: center;padding-bottom:20px;padding-top:10px"><h1>Comportement des Systèmes Continus</h1>
    <h2>Labo 1</h2>
</div>

### But de l'étude.

La première partie de ce TP concerne l'analyse du comportement temporel et fréquentiel des systèmes continus. En plus d'un rappel sur les Fonctions de Transfert (FT) du 1er ordre et 2ème ordre, cette partie permet de prendre progressivement connaissance de l'environnement Jupyter  et plus particulièrement de la librairie `Python Control` concernant les F.T et de la librairie `ENIB_control` pour l'affichage des courbes.

Dans une deuxième partie, diverses synthèses de correcteurs analogiques sont réalisées. Le calcul de correcteurs et la validation des résultats se feront en utilisant au maximum les fonctionnalités de la librairie `Python Control`.

### Documentations

<div class="alert alert-info">
    La documentation de la librairie Python Control est disponible à l'adresse: <a href="https://python-control.readthedocs.io/en/0.8.3/">Python Control</a>.
</div>

<div class="alert alert-info">
    La documentation de la librairie Enib Control est disponible à l'adresse: <a href="./documentation2.ipynb">documentation2.ipynb</a>.
</div>

<div class="alert alert-info">
    Pour les systèmes de second ordre, les abaques sont disponibles à l'adresse: <a href="https://vincentchoqueuse.github.io/web_app_2nd_order_performances/index.html">abaques</a>.
</div>





In [1]:
import numpy as np
from ENIB_control import *
from control import *

### 1. Analyse en temps et en fréquence des fonctions de transfert 

La fonction `tf` de la librairie `Python Control` permet de créer une fonction de transfert $F(p)$. Il s'agit d'une classe particulière de variables avec ses propres propriétés et ses propres opérations.

Pour nous entrainer, nous allons considérer les fonctions de transfert suivantes:

$$F_1(p)=\frac{2}{1+3p}$$
$$F_2(p)=\frac{2}{1+10p+2p^2}$$
$$F_3(p)=\frac{2}{1+0.5p+8p^2}$$

#### Saisie du Système

La commande `tf` permet la saisie de la F.T. sous forme polynomiale (voir <a href="https://python-control.readthedocs.io/en/0.8.3/generated/control.tf.html">documentation</a>)

**Question :** Saisissez les fonctions de transfert continue $F_1(p)$, $F_2(p)$ et $F_3(p)$ sous forme polynomiale.

In [2]:
F1 = tf([2],[3,1])
F2 = tf([2],[2,10,1])
F3 = tf([2],[8,0.5,1])

print (F1,F2,F3)


   2
-------
3 s + 1
 
       2
----------------
2 s^2 + 10 s + 1
 
        2
-----------------
8 s^2 + 0.5 s + 1



**Question :** Déterminez les pôles de chacun des 3 systèmes.

In [3]:
print (pole(F1))
print (pole(F2))
print (pole(F3))

[-0.33333333]
[-4.89791576 -0.10208424]
[-0.03125+0.35216961j -0.03125-0.35216961j]


#### 2.1 Analyse temporelle

##### Réponse à une impulsion

On appelle réponse impulsionnelle, la réponse temporelle à une impulsion en entrée pour un système linéaire initialement au repos, elle permet de déterminer expérimentalement la stabilité du système. Un système linéaire est stable si la réponse impulsionnelle $f(t)$ tend vers $0$ lorsque t tend vers l’infini. L’étude théorique explique qu’un système linéaire est stable si tous ses pôles (racines du dénominateur) sont à partie réelle négative.

**Question :**

* Tracez la réponse impulsionnelle de $F_1(p)$ via la fonction `figure("time")` et l'argument `type="impulse"`
* Retrouvez par le calcul l'expression théorique de la réponse impulsionnelle.

In [22]:
impulse([F1])

In [5]:
impulse([F2],500)

In [6]:
impulse([F3],400)

##### Réponse à un échelon

On appelle réponse indicielle, la réponse temporelle à un échelon en entrée pour un système linéaire initialement au repos, elle permet de déterminer expérimentalement la rapidité du système.

**Question :**

* Tracez la réponse indicielle des différentes fonction de transfert. 
* Retrouvez par le calcul l'expression théorique de la réponse indicielle.

In [7]:
step([F1])

**Question :**

En utilisant la fonction `stepinfo`, déterminez pour la réponse indicielle de la fonction de transfert $F_1(p)$:
* le temps de réponse à $\pm 5 \%$,
* le temps de montée de $10\%$ à $90\%$,
* la valeur finale.

In [8]:
stepinfo(F1)
#stepinfo(F2)
#stepinfo(F3)

{'RiseTime': 6.648241206030151,
 'SettlingTime': 8.969849246231156,
 'SettlingMin': 1.8037686305649496,
 'SettlingMax': 1.9981762360688888,
 'Overshoot': 0.0,
 'Undershoot': 0.0,
 'Peak': 1.9981762360688888,
 'PeakTime': 21.0,
 'SteadyStateValue': 1.9981762360688888}

**Question :**

Completez le tableau suivant pour les 3 fonctions de transfert. La valeur de $m$ pourra s'obtenir au moyen de la fonction `damp`.

<table>
    <tr>
        <th>Fonction de Transfert</th>
        <th style="width: 25%">$F_1(p)$</th>
        <th style="width: 25%">$F_2(p)$</th>
        <th style="width: 25%">$F_3(p)$</th>
    </tr>
    <tr>
        <td>$t_r (\pm 5\%)$</td>
        <td></td>
        <td></td>
        <td></td>
    </tr> 
    <tr>
        <td>$m$</td>
        <td></td>
        <td></td>
        <td></td>
    </tr> 
    <tr>
        <td>$D_r(\%)$</td>
        <td></td>
        <td></td>
        <td></td>
    </tr> 
    <tr>
        <td>$s(\infty)$</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>

**Question :**
    
Que pouvez-vous conclure sur les pôles de ces FT à partir du coefficient d'amortissement ou du dépassement ?

si ordre 2  si m>1 poles réels                 pas de dépassement
            si m<1 poles complexes conjugues   +dépassement

#### 2.2 Analyse Fréquentielle

La réponse harmonique ou réponse fréquentielle permet d'analyser la réponse temporelle du système à une entrée sinusoïdale en régime permanent par une lecture directe du module (coefficient d'amplification ou d'atténuation) et de la phase (avance ou retard) pour toutes les fréquences du signal d'entrée. Cette analyse permet d'évaluer les performances en régime dynamique telles que la bande passante, le filtrage, le déphasage du processus.

On rappelle que la réponse harmonique est obtenue en étudiant le gain et la phase de la fonction complexe $F(j\omega)$ correspondant à $F(p)$ où on remplace $p = j\omega$ ( $\omega$ : pulsation réelle du signal d'entrée).
La réponse harmonique peut être visualisée sous différentes formes : Bode, Nyquist, ou Black-Nichols en utilisant la fonction `figure()`


##### Diagramme de Bode

**Question :** Visualisez les diagrammes de Bode des 3 fonctions de transfert. Analysez le comportement de chacune d'elle.

In [9]:
#mag,phase,w = bode_plot(F1,dB=True)
fig = figure("bode")
fig.plot(F1)
fig.plot(F2)
fig.plot(F3)
fig.show()

C:\Users\carre\anaconda3\lib\site-packages\control\freqplot.py:163: FutureWarning:

'Plot' keyword is deprecated in bode_plot; use 'plot'



**Question :** Complétez le tableau suivant à l'aide de Python (voir annexe polycopié de cours pour la définition de certains paramètres).

<table>
    <tr>
        <th>Fonction de Transfert</th>
        <th style="width: 25%">$F_1(p)$</th>
        <th style="width: 25%">$F_2(p)$</th>
        <th style="width: 25%">$F_3(p)$</th>
    </tr>
    <tr>
        <td>Gain Statique (dB)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr> 
    <tr>
        <td>Phase à l'origine (deg)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr> 
    <tr>
        <td>Gain pour $\omega \to \infty$ (dB)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr> 
    <tr>
        <td>Phase pour $\omega \to \infty$ (deg)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Pulsation de résonance (rad/s)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Coefficient de résonance (dB)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Coefficient de qualité (dB)</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>

##### Diagramme de Black NIchols

**Question :** Visualisez les diagrammes de Black des 3 fonctions de transfert. Retrouvez visuellement les caractéristiques du tableau précédent.

In [10]:
fig = figure("nichols")
fig.plot(F1,w=np.logspace(-0.5,2,100))
fig.plot(5*F1)
fig.grid(cm=np.array([6,0,-5,-20]))
fig.show()

### 2. Correction d'un système du 2nd ordre.

#### 2.1 Analyse du système en boucle fermée

On considère un système du second ordre continu incorporé dans une boucle d'asservissement avec un correcteur proportionnel $K_c$ et un retour unitaire.

<img src="img/labo1_1.png" style="width: 500px">

avec la fonction de transfert suivante :

$$F(p)=\frac{8}{(1+0.1p)(1+0.01p)}$$

##### Analyse temporelle ($Kc=1$)

On pose initialement $K_c=1$.

**Question :**
* Déterminez la fonction de transfert en boucle fermée (FTBF) $H(p)$ avec la fonction `feedback`. 
* Vérifiez que vous retrouvez $H(p)$ théoriquement

In [11]:
F = series(tf([8],[0.1,1]),tf([1],[0.01,1]))
print(F)
H = feedback(F,1)
print(H)


          8
----------------------
0.001 s^2 + 0.11 s + 1


          8
----------------------
0.001 s^2 + 0.11 s + 9



**Question :**
* Pour le système en boucle fermée, simulez la réponse indicielle puis complétez le tableau suivant :

<table style="width: 100%">
    <tr style="width: 100%">
        <th style="width: 20%"></th>
        <th style="width: 20%">$t_r$</th> 
        <th style="width: 20%">$m$</th> 
        <th style="width: 20%">$D\%$</th> 
        <th style="width: 20%">$s(\infty)$</th> 
    </tr>
    <tr>
        <td>$H(p)$</td>
         <td>??? </td>
         <td>??? </td>
         <td>???</td>
         <td>??? </td>
    </tr>
</table>

In [12]:
stepinfo(H)
#0.005 0.56 10.6 0.89

{'RiseTime': 0.01854728186386477,
 'SettlingTime': 0.05564184559159432,
 'SettlingMin': 0.8012887894678292,
 'SettlingMax': 0.9839252175531522,
 'Overshoot': 10.570438930324531,
 'Undershoot': 0.0,
 'Peak': 0.9839252175531522,
 'PeakTime': 0.04093193238921881,
 'SteadyStateValue': 0.8898628124042886}

In [13]:
damp(H)

_____Eigenvalue______ Damping___ Frequency_
       -55     +77.3j     0.5798      94.87
       -55     -77.3j     0.5798      94.87


(array([94.86832981, 94.86832981]),
 array([0.5797509, 0.5797509]),
 array([-55.+77.29812417j, -55.-77.29812417j]))

##### Réponse fréquentielle de $H(p)$ ($K_c=1$) 

On s'interesse maintenant au diagramme de Black-Nichols

**Question :** 

* Tracez la réponse fréquentielle dans le plan de Black-Nichols de la **fonction de transfert en boucle ouverte** $F(p)$
* A partir du tracé dans le plan de Black-Nichols, complétez le tableau suivant pour la FTBO $F(p)$. A partir des contours d'isogain, complétez également le tableau pour la fonction de transfert en boucle fermée $H(p)$. 
* Vérifiez que vous obtenez pour $F(p)$ et $H(p)$ les mêmes résultats lors de l'analyse de Bode.

In [14]:
fig = figure("nichols")
fig.plot(F,w=np.logspace(-2,3,200))
fig.grid(cm=np.array([6,3, 1, 0.5,0, -1, -3, -5, -10, -15, -20]))
fig.show()

<table style="width: 100%">
    <tr style="width: 100%">
        <th >Système</th>
        <th >$\omega$ (rad/s)</th> 
        <th >0</th> 
        <th >5</th> 
        <th >10</th>
        <th >20</th> 
        <th >30</th> 
        <th >50</th> 
        <th >100</th> 
        <th >500</th>
        <th >1000</th>
        <th >$\infty$</th>
    </tr>
    <tr>
        <td> $F(p)$ </td>
         <td>gain (dB)</td>
         <td>18</td>
         <td>17</td>
         <td>15</td>
         <td>10</td>
         <td>8</td>
         <td>3</td>
         <td>-5</td>
         <td>-30</td>
         <td>-42</td>
        <td>-$\infty$</td>
    </tr>
    <tr>
        <td> $F(p)$ </td>
         <td>Phase (deg)</td>
         <td>0</td>
         <td>-30</td>
         <td>-50</td>
         <td>-73</td>
         <td>-88</td>
         <td>-105</td>
         <td>-129</td>
         <td>-168</td>
         <td>-174</td>
        <td>-180</td>
    </tr>
        <tr>
        <td> $H(p)$ </td>
         <td>gain (dB)</td>
         <td>-1</td>
         <td>-1</td>
         <td>-1</td>
         <td>-1</td>
         <td>-1</td>
         <td>-1</td>
         <td></td>
         <td></td>
         <td></td>
        <td>-$\infty$</td>
    </tr>
    <tr>
        <td> $H(p)$ </td>
         <td>Phase (deg)</td>
         <td>-1</td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
         <td></td>
        <td>-180</td>
    </tr>
</table>

#### Stabilité de $H(p)$ ($K_c=1$)

**Question :** 

* Énoncez le critère de stabilité dans ce lieu.
* Concluez quant à la stabilité de $H(p)$ à partir du lieu de Black-Nichols.


### 2.2 Correction proportionnel du système à asservir 


**Question :** 

* Déterminez par essais successifs le gain $K_c$ à introduire dans la chaîne pour obtenir un comportement de la fonction de transfert en boucle fermée comparable à celui d'un système du 2ème ordre présentant un dépassement relatif de $D_r=25\%$.

* Déterminez les caractéristiques temporelles de la fonction de transfert corrigée et bouclée par le gain $K_c$.


In [24]:
Kc=4

fig = figure("nichols")
fig.plot(F,w=np.logspace(-2,3,200))
fig.plot(Kc*F,w=np.logspace(-2,3,200))
fig.grid(cm=np.array([6,4.5, 5, 3, 1, 0.5,0, -0.3, -1, -3, -5, -10, -15, -20]))
fig.show()

In [25]:
H = feedback(Kc*F, 1, sign=-1)
print(H)


          32
-----------------------
0.001 s^2 + 0.11 s + 33



In [26]:
damp(H)

_____Eigenvalue______ Damping___ Frequency_
       -55    +173.1j     0.3028      181.7
       -55    -173.1j     0.3028      181.7


(array([181.65902125, 181.65902125]),
 array([0.30276504, 0.30276504]),
 array([-55.+173.13289693j, -55.-173.13289693j]))

In [18]:
step([H])

In [19]:
stepinfo(H)

{'RiseTime': 0.010232983097304704,
 'SettlingTime': 0.055641845591594324,
 'SettlingMin': 0.8649809553046413,
 'SettlingMax': 1.1941167051408819,
 'Overshoot': 25.778448417957936,
 'Undershoot': 0.0,
 'Peak': 1.1941167051408819,
 'PeakTime': 0.02430333485609867,
 'SteadyStateValue': 0.9493810109446322}